### ISSUE TITLE
Retrieving solution breaks when solution contains a *.deployproj project

### ISSUE THREAD

**Issue by wouterroos** [3F/MvsSln#14]
```
using (var sln = new Sln(solutionPath, SlnItems.All & ~SlnItems.ProjectDependencies))
{
}
```

Above code breaks when solution contains a *.deployproj project (used for Azure Resource Group deployments).

**Comment by wouterroos** [comment]
Hi, 

I created #15 to fix the issue, the project type guid for *.deployproj files is not known within your library. I also added the correct guid for Service Fabric (*.sfproj) project since I will be needing that as well for my project.

**Comment by 3F** [comment]
> breaks when solution contains

**By the way,** this is not correct behavior! Broken after 2.1. Seems I forgot to process `ProjectType.Unknown` case:

https://github.com/3F/MvsSln/blob/97896c4ceec97edd76b303a337a6e4e2f553fd67/MvsSln/Core/Guids.cs#L68

Also, this is not optimized because of full processing from `Where` clause -_-

I can fix this later or you.

**Comment by 3F** [comment]
Yes, confirmed. **v2.1** works fine when some guids are not presented in our lib. 
It's bug of the new 2.2

**Comment by wouterroos** [comment]
Hi,

Thanks for investigating. I tried reverting to 2.1 to see if that could unblock me for my project, unfortunately I now run into the issue below (that has been fixed in 2.2).

* FIXED: Fixed possible error when loading all found projects:
        'An equivalent project is already present in the project collection, ...'

**Comment by wouterroos** [comment]
I updated #15 with a fix for the lookup of unknown project types.

**Comment by 3F** [comment]
Approved. Thanks again!

**Comment by wouterroos** [comment]
@3F Any ETA on when this will be available on NuGet?

**Comment by 3F** [comment]
planned for 2.3 (see related milestone)

I've plan to fix this to the end of this week. This is a very trivial 
but major error.
Or you can. Then I will just raise the release for all public channels ASAP.

Currently you also can use this via CI-builds on GHR
