### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found. 

### ISSUE THREAD

**Issue by arivera12** [3F/MvsSln#24]
I am trying to add a project reference to a solution and this error message gets throw.

This is the code that throws the error.

`sln.Result.Env.AddOrGet(new Project(XmlReader.Create(new StreamReader($@".\Solutions\{Namespace}\{Namespace}.Server\{Namespace}.Server.csproj"))));`

I have net core sdk installed but couldn't figure out why this error occurs.

**Comment by 3F** [comment]
Check this out for 2.x: https://github.com/3F/MvsSln/wiki/Advanced-Features#custom-msbuild-resolver

**Comment by arivera12** [comment]
After trying to above solution its throws me an error when calling builder resolver telling me that the sdk have been already loaded. I added my own implementation for my needs. Thanks anyway.

**Comment by 3F** [comment]
> I added my own implementation for my needs.

I am a bit confused with your applied solution if we're talking about project files. 
Because it sounds you are doing something wrong:

Either you don't need msbuild resolver at all, or manipulations with xml-nodes + compatible evaluator engine are just a separate conversation which is more likely related to the planned v3.0 and so on.

**Comment by arivera12** [comment]
Don't worry I just needed to add some items to a static project file.

**Comment by 3F** [comment]
I see. XDocument-like solution could be really a good option for your 
case. The other cases with correct evaluated nodes should be processed 
through Sdk-resolvers (abstract layer in build.framework part). But 
means only modern project files and not .sln features where you can 
easily add something through related `ProjectItem` etc.

My hope for v3 that probably will fix the mentioned situation. Time will 
tell, follow the news.
