### ISSUE TITLE
Create Solution Folder

### ISSUE THREAD

**Issue by SirPolly** [3F/MvsSln#6]
Hello,

as far as I can see, I can't create new project folders or assign projects to folder. Our build system generates a flat list of 400 C++ projects and I want to categorize them.

**Comment by 3F** [comment]
Solution Folders(items) **are possible** through:

* LProjectSolutionItems  (reader handler)
* WProjectSolutionItems  (writer handler)

```csharp
    IEnumerable<SolutionFolder> SolutionFolders
```

So you can try to create new folder and/or its items in the same manner like from [my example here](https://github.com/3F/MvsSln/issues/3#issuecomment-350589040).
* Just create/modify list of [SolutionFolder](https://github.com/3F/MvsSln/blob/master/MvsSln/Core/SolutionFolder.cs) instances. Then push vice versa through related writer.

Let me know if you can't something, I'll prepare some example later.

**Comment by SirPolly** [comment]
Thank you for your fast response. I still don't really know how to use the API:
```C#
using (var sln = new Sln(args[0], SlnItems.Header | SlnItems.Projects | SlnItems.SolutionItems)) {
    var folders = sln.Result.SolutionFolders.ToList();
    folders.Add(new SolutionFolder(...)); // What to insert here? ProjectItem has only one ctor; IEnumerable<RawText> def is a text list of guids I guess?

    var whandlers = new Dictionary<Type, HandlerValue>() {
        [typeof(LProjectSolutionItems)] = new HandlerValue(new WProjectSolutionItems(folders)),
    };

    using (var w = new SlnWriter(args[0] + ".better", whandlers)) {
        w.Write(sln.Result.Map);
    }
}
```

Thank you :)

**Comment by SirPolly** [comment]
This is the code I have up until now. The generated file is empty tho.

```C#
            using (var sln = new Sln(args[0], SlnItems.Header | SlnItems.Projects | SlnItems.SolutionItems | SlnItems.SolutionConfPlatforms | SlnItems.ProjectConfPlatforms)) {
                var folders = new List<SolutionFolder>();
                if (sln.Result.SolutionFolders != null) {
                    folders = sln.Result.SolutionFolders.ToList();
                }
                
                var folderName = "Test";
                var folderGuid = Guid.NewGuid();
                var item = new ProjectItem("Project(\"{2150E333-8FDC-42A3-9474-1A3956D46DE8}\") = \"" + folderName + "\", \"" + folderName + "\", \"{" + folderGuid + "}\"", null);
                folders.Add(new SolutionFolder(item, null));

                var whandlers = new Dictionary<Type, HandlerValue>() {
                    [typeof(LProjectSolutionItems)] = new HandlerValue(new WProjectSolutionItems(folders)),
                };

                using (var w = new SlnWriter(args[0] + ".better", whandlers)) {
                    w.Write(sln.Result.Map);
                }
            }
```

**Comment by SirPolly** [comment]
Any clue on how to get the NestedProjects section populated?
```
GlobalSection(NestedProjects) = preSolution
    {9E2D0B92-DA21-418C-9F9A-3C896110B992} = {2E05BAA3-EB03-46F9-8C52-232DB0D837EB}
EndGlobalSection
```
SolutionFolder takes a list of RawTexts for single files, but no projects? Quick hint please :D

**Comment by 3F** [comment]
Today's way for creating solution folder looks like:

```csharp
var folders = new List<SolutionFolder>(sln.Result.SolutionFolders)
{
    new SolutionFolder
    (
        new ProjectItem()
        {
            pType = Guids.SLN_FOLDER,
            name = "MyFolder1",
            path = "MyFolder1", // recommended to be same
            pGuid = Guid.NewGuid().ToString()
        },
        new List<RawText>()
        {
            ".gnt\\gnt.core",
            ".gnt\\packages.config",
            // ...
        }
    ),
    //...
};
```

handlers for this case as I said:

```csharp
var whandlers = new Dictionary<Type, HandlerValue>() {
    [typeof(LProjectSolutionItems)] = new HandlerValue(new WProjectSolutionItems(folders)),
};
```


But seems we have no handlers for `NestedProjects` when solution folders, sorry for the inconvenience :(

I've plan to implement this, follow the news.

**Comment by 3F** [comment]
> Any clue on how to get the NestedProjects section 

ah yes, forgot to say about map. I don't recommend this, but anyway, just for clarify before support.

In any case, you can easily get access to any lines of loaded .sln.

As it was illustrated:

![](https://raw.githubusercontent.com/3F/MvsSln/master/resources/MvsSln_v2.0_Map.png)

The `Map` property from result contains all lines which are already processed with handlers and which are still not.

So we can get anything to manual processing. However, *this is not recommended way.*

Because I specially prepared flexible architecture to add any custom handlers (including user space) for any lines which are still not processed (or for multiple processing).

Thus, **temporarily** you can try to add your custom handler, then just register it in listeners for common use.

I think we need also add some documentation for this <_<

But of course, MvsSln should support this by default. Ticket above.

**Comment by SirPolly** [comment]
Thank you for your quick answer :)

I decided to implement this with a rather long python script. It's crude but it does the job. A list of things to consider when implementing this might help you:
- folders inside folders
- folders having the same name on different levels of the tree
- moving projects into folders
- getting or creating a folder with the same method (GetOrCreateFolder)

**Comment by 3F** [comment]
It will be implemented later anyway. At least by me. 

In fact, the main features was extracted from [vsSolutionBuildEvent](https://github.com/3F/vsSolutionBuildEvent) project. Mainly for [DllExport](https://github.com/3F/DllExport), but I also had plans in past for just splitting something like this including its script engine etc.

That is, this feature was simply not required to someone(including me) for all that period :)

But MvsSln should really cover it. Basically, we just need to implement ISlnHandler and IObjHandler with related logic for new handlers. It shouldn't be hard.

I will look into later. More probably this March, well, as possible for my time. Also follow the new issue.

**Comment by 3F** [comment]
You can test new features starting from CI-build-37 https://github.com/3F/MvsSln/releases

[Planned for 2.2](https://github.com/3F/MvsSln/milestones)

```csharp
new SolutionFolder("dir1", 
    new SolutionFolder("dir2", 
        new SolutionFolder("dir3", "hMSBuild.bat", "DllExport.bat")
    )
);
...
new ProjectItem("Project1", ProjectType.Cs, new SolutionFolder("dir1"));
```

https://github.com/3F/MvsSln/issues/8#issuecomment-478596679



> getting or creating a folder with the same method (GetOrCreateFolder)

It's beyond of this project. You can easily use it manually from your app. However, you can also create new issue for suggest this feature. It will be considered later.
