### ISSUE TITLE
Getting projects *in build order* from .sln

### ISSUE THREAD

**Issue by DynConcepts** [3F/MvsSln#60]
Is there any pre-existing code that will take a solution file, a configuration/platform, and return all of the projects to be build -- in the correct order?

**Comment by 3F** [comment]
Hello,

The order depends on your actual goal. If you need to consider dependencies in attempt to construct list of records for correct build, yes, of course, MvsSln helps in this way with the [ISlnPDManager](https://github.com/3F/MvsSln/blob/master/MvsSln/Core/ISlnPDManager.cs) and [ISlnProjectDependencies](https://github.com/3F/MvsSln/blob/master/MvsSln/Core/ISlnProjectDependencies.cs)

https://github.com/3F/MvsSln/blob/8d847f0f15622107663111ec4d423fed50f71b78/MvsSln/SlnItems.cs#L58-L60

Specific implementation should be provided automatically (you don't need to do anything else) same together with *SlnResult* if applied `ProjectDependencies`

https://github.com/3F/MvsSln/blob/8d847f0f15622107663111ec4d423fed50f71b78/MvsSln/Core/SlnResult.cs#L121-L124

Using *ISlnPDManager* is very easy but [**here**](https://github.com/3F/DllExport/blob/master/RGiesecke.DllExport.MSBuild/PostProc.cs) you can find full example in real project. There we [discussed](https://github.com/3F/DllExport/pull/148) various cases that can affect on projects build and their dependencies.

Let me know if this doesn't fit the issue.

**Comment by 3F** [comment]
I close the issue. Please provide further details if the problem still exists.
